"https://rubygems.org/api/v1/gems/rspec.json":
  status: 200
  body: |
    {
      "name": "rspec",
      "downloads": 145999055,
      "version": "3.7.0",
      "version_downloads": 20169199,
      "platform": "ruby",
      "authors": "Steven Baker, David Chelimsky, Myron Marston",
      "info": "BDD for Ruby",
      "licenses": [
        "MIT"
      ],
      "metadata": {},
      "sha": "0174cfbed780e42aa181227af623e2ae37511f20a2fdfec48b54f6cf4d7a6404",
      "project_uri": "https://rubygems.org/gems/rspec",
      "gem_uri": "https://rubygems.org/gems/rspec-3.7.0.gem",
      "homepage_uri": "http://github.com/rspec",
      "wiki_uri": "",
      "documentation_uri": "http://relishapp.com/rspec",
      "mailing_list_uri": "http://rubyforge.org/mailman/listinfo/rspec-users",
      "source_code_uri": "http://github.com/rspec/rspec",
      "bug_tracker_uri": "",
      "changelog_uri": null,
      "dependencies": {
        "development": [],
        "runtime": [
          {
            "name": "rspec-core",
            "requirements": "~> 3.7.0"
          },
          {
            "name": "rspec-expectations",
            "requirements": "~> 3.7.0"
          },
          {
            "name": "rspec-mocks",
            "requirements": "~> 3.7.0"
          }
        ]
      }
    }

"https://rubygems.org/api/v1/gems/rspec/reverse_dependencies.json":
  status: 200
  body: |
    ["rspec-fixture", "rspec-file-transfer-matchers", "rkid", "rbehave", "quicktest", "picolena"]

"https://rubygems.org/api/v1/versions/rspec.json":
  status: 200
  body: |
    [{
      "authors": "Steven Baker, David Chelimsky, Myron Marston",
      "built_at": "2017-10-17T00:00:00.000Z",
      "created_at": "2017-10-17T15:12:32.872Z",
      "description": "BDD for Ruby",
      "downloads_count": 23558708,
      "metadata": {},
      "number": "3.7.0",
      "summary": "rspec-3.7.0",
      "platform": "ruby",
      "rubygems_version": "\u003e= 0",
      "ruby_version": "\u003e= 0",
      "prerelease": false,
      "licenses": ["MIT"],
      "requirements": [],
      "sha": "0174cfbed780e42aa181227af623e2ae37511f20a2fdfec48b54f6cf4d7a6404"
    }, {
      "authors": "Steven Baker, David Chelimsky, Myron Marston",
      "built_at": "2017-05-04T00:00:00.000Z",
      "created_at": "2017-05-04T23:58:19.430Z",
      "description": "BDD for Ruby",
      "downloads_count": 41425604,
      "metadata": {},
      "number": "3.6.0",
      "summary": "rspec-3.6.0",
      "platform": "ruby",
      "rubygems_version": "\u003e= 0",
      "ruby_version": "\u003e= 0",
      "prerelease": false,
      "licenses": ["MIT"],
      "requirements": [],
      "sha": "ebc3d479cf2f144b3deef5d72dbb1cc6a15750899d26a8da164a2cc53c04a5d9"
    }, {
      "authors": "Steven Baker",
      "built_at": "2005-08-11T04:00:00.000Z",
      "created_at": "2009-07-25T17:56:49.000Z",
      "description": "RSpec is a behaviour specification framework for Ruby.  RSpec was created in response to Dave Astels' article _A New Look at Test Driven Development_ which can be read at: http://daveastels.com/index.php?p=5  RSpec is intended to provide the features discussed in Dave's article.",
      "downloads_count": 2298,
      "metadata": {},
      "number": "0.1.0",
      "summary": "Behaviour Specification Framework for Ruby",
      "platform": "ruby",
      "rubygems_version": "\u003e= 0",
      "ruby_version": null,
      "prerelease": false,
      "licenses": null,
      "requirements": null,
      "sha": "b59c1eb10f74c00b28cdb771618814a863bbfaa5a92314d92868c59850720300"
    }]

"https://rubygems.org/api/v1/gems/thisisdowninmock.json":
  status: 500

"https://api.github.com/repos/rails/rails":
  status: 200
  body: |
    {
      "id": 8514,
      "name": "rails",
      "full_name": "rails/rails",
      "owner": {
        "login": "rails",
        "id": 4223,
        "avatar_url": "https://avatars1.githubusercontent.com/u/4223?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rails",
        "html_url": "https://github.com/rails",
        "followers_url": "https://api.github.com/users/rails/followers",
        "following_url": "https://api.github.com/users/rails/following{/other_user}",
        "gists_url": "https://api.github.com/users/rails/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rails/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rails/subscriptions",
        "organizations_url": "https://api.github.com/users/rails/orgs",
        "repos_url": "https://api.github.com/users/rails/repos",
        "events_url": "https://api.github.com/users/rails/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rails/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/rails/rails",
      "description": "Ruby on Rails",
      "fork": false,
      "url": "https://api.github.com/repos/rails/rails",
      "forks_url": "https://api.github.com/repos/rails/rails/forks",
      "keys_url": "https://api.github.com/repos/rails/rails/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/rails/rails/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/rails/rails/teams",
      "hooks_url": "https://api.github.com/repos/rails/rails/hooks",
      "issue_events_url": "https://api.github.com/repos/rails/rails/issues/events{/number}",
      "events_url": "https://api.github.com/repos/rails/rails/events",
      "assignees_url": "https://api.github.com/repos/rails/rails/assignees{/user}",
      "branches_url": "https://api.github.com/repos/rails/rails/branches{/branch}",
      "tags_url": "https://api.github.com/repos/rails/rails/tags",
      "blobs_url": "https://api.github.com/repos/rails/rails/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/rails/rails/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/rails/rails/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/rails/rails/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/rails/rails/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/rails/rails/languages",
      "stargazers_url": "https://api.github.com/repos/rails/rails/stargazers",
      "contributors_url": "https://api.github.com/repos/rails/rails/contributors",
      "subscribers_url": "https://api.github.com/repos/rails/rails/subscribers",
      "subscription_url": "https://api.github.com/repos/rails/rails/subscription",
      "commits_url": "https://api.github.com/repos/rails/rails/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/rails/rails/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/rails/rails/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/rails/rails/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/rails/rails/contents/{+path}",
      "compare_url": "https://api.github.com/repos/rails/rails/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/rails/rails/merges",
      "archive_url": "https://api.github.com/repos/rails/rails/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/rails/rails/downloads",
      "issues_url": "https://api.github.com/repos/rails/rails/issues{/number}",
      "pulls_url": "https://api.github.com/repos/rails/rails/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/rails/rails/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/rails/rails/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/rails/rails/labels{/name}",
      "releases_url": "https://api.github.com/repos/rails/rails/releases{/id}",
      "deployments_url": "https://api.github.com/repos/rails/rails/deployments",
      "created_at": "2008-04-11T02:19:47Z",
      "updated_at": "2018-01-03T21:10:44Z",
      "pushed_at": "2018-01-03T22:39:06Z",
      "git_url": "git://github.com/rails/rails.git",
      "ssh_url": "git@github.com:rails/rails.git",
      "clone_url": "https://github.com/rails/rails.git",
      "svn_url": "https://github.com/rails/rails",
      "homepage": "http://rubyonrails.org",
      "size": 157707,
      "stargazers_count": 38140,
      "watchers_count": 38140,
      "language": "Ruby",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 15500,
      "mirror_url": null,
      "archived": false,
      "open_issues_count": 1123,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit"
      },
      "forks": 15500,
      "open_issues": 1123,
      "watchers": 38140,
      "default_branch": "main",
      "organization": {
        "login": "rails",
        "id": 4223,
        "avatar_url": "https://avatars1.githubusercontent.com/u/4223?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rails",
        "html_url": "https://github.com/rails",
        "followers_url": "https://api.github.com/users/rails/followers",
        "following_url": "https://api.github.com/users/rails/following{/other_user}",
        "gists_url": "https://api.github.com/users/rails/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rails/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rails/subscriptions",
        "organizations_url": "https://api.github.com/users/rails/orgs",
        "repos_url": "https://api.github.com/users/rails/repos",
        "events_url": "https://api.github.com/users/rails/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rails/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "network_count": 15500,
      "subscribers_count": 2520
    }


"https://api.github.com/repos/ohnogithub/isdown":
  status: 500

